"""empty message

Revision ID: 0b378e8bff16
Revises: 53e019dac537
Create Date: 2022-04-16 13:50:09.706452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b378e8bff16'
down_revision = '53e019dac537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chef', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chef', sa.Column('slug', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
