"""empty message

Revision ID: 53e019dac537
Revises: 0485301b9a9a
Create Date: 2022-04-16 13:09:04.832172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e019dac537'
down_revision = '0485301b9a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chef', sa.Column('image', sa.String(length=250), nullable=True))
    op.add_column('recipe', sa.Column('image', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image')
    op.drop_column('chef', 'image')
    # ### end Alembic commands ###
